# Generated by Django 4.0.1 on 2022-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poster'),
        ),
    ]
