# Generated by Django 4.0.1 on 2022-01-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
