# Generated by Django 4.0.1 on 2022-01-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('year', models.DateField(max_length=50, verbose_name='장르')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('star', models.CharField(max_length=50, verbose_name='별점')),
                ('time', models.CharField(max_length=50, verbose_name='러닝타임')),
                ('content', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actor', models.CharField(max_length=50, verbose_name='배우')),
            ],
        ),
    ]
