# Generated by Django 4.0.1 on 2022-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.CharField(max_length=50, verbose_name='개봉 년도'),
        ),
    ]
