# Generated by Django 4.0.1 on 2022-01-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.FloatField(max_length=50, verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.IntegerField(max_length=50, verbose_name='러닝타임'),
        ),
    ]
